name: 'Yarn Tests'
description: 'Check Licenses, Start Flow Server, Yarn Test'
inputs: {}
outputs: {}
runs:
  using: "composite"
  steps:
    - id: check-licenses
      run: |
        echo "::group::Check Licenses"
        yarn build:license-checker
        echo "::endgroup::"
      shell: bash
    - id: start-flow-server
      run: |
        echo "::group::Star Flow Server"
        yarn flow start
        echo "::endgroup::"
      shell: bash
    - id: yarn-test
      run: |
        echo "::group::yarn test"
        yarn test
        echo "::endgroup::"
      shell: bash
