name: 'Yarn Tests'
description: 'Check Licenses, Start Flow Server, Yarn Test'
inputs:
  args:
    description: "Additional arguments for yarn test command"
    default: ""
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Check Licenses
      id: check-licenses
      run: |
        echo "::group::Check Licenses"
        yarn build:license-checker
        echo "::endgroup::"
      shell: bash
    - name: Start Flow Server
      id: start-flow-server
      run: |
        echo "::group::Star Flow Server"
        yarn flow start
        echo "::endgroup::"
      shell: bash
    - name: Yarn test
      id: yarn-test
      run: |
        echo "::group::yarn test"
        args+=(${{ inputs.args }})
        yarn test "${args[@]}"
        echo "::endgroup::"
      shell: bash
